baseURL = 'https://easyctf-one.github.io/'
title = 'EasyCTF Blog'
theme = 'hugo-theme-reimu'
languageCode = 'zh-CN'
defaultContentLanguage = 'zh-CN'
[languages]
[languages.zh-CN]
languageName = '简体中文'
weight = 1
[markup.highlight]
guessSyntax = true
noClasses = false
[outputs]
home = ["Algolia", "HTML", "RSS"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true